### ISSUE TITLE
Todo for first release

### ISSUE THREAD

**Issue by luukholleman** [ParkitectNexus/Website#1]
- [x] Asset, like, post count for user
- [x] Homepage
- [x] Notifications
- [ ] Recap email
- [x] Like buttons
- [x] Screenshots
- [x] Script for seeding with old database
- [x] Profile page
- [x] Account settings
- [x] Client support
- [x] Likes for forum
- [x] Tracking of views/downloads
- [x] Download/install assets
- [x] Automatic image resizing
- [x] Update assets
- [x] Register downloads on client install
- [x] Client download page
- [x] Fix filters
- [x] Client log
